# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/terenctb/Project/bigbadrobots/brutal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/terenctb/Project/bigbadrobots/brutal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/terenctb/Project/bigbadrobots/brutal/CMakeFiles /home/terenctb/Project/bigbadrobots/brutal//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/terenctb/Project/bigbadrobots/brutal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named brutal

# Build rule for target.
brutal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 brutal
.PHONY : brutal

# fast build rule for target.
brutal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/build
.PHONY : brutal/fast

#=============================================================================
# Target rules for targets named brutal_test

# Build rule for target.
brutal_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 brutal_test
.PHONY : brutal_test

# fast build rule for target.
brutal_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/build
.PHONY : brutal_test/fast

src/game/gameobject.o: src/game/gameobject.cpp.o
.PHONY : src/game/gameobject.o

# target to build an object file
src/game/gameobject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/game/gameobject.cpp.o
.PHONY : src/game/gameobject.cpp.o

src/game/gameobject.i: src/game/gameobject.cpp.i
.PHONY : src/game/gameobject.i

# target to preprocess a source file
src/game/gameobject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/game/gameobject.cpp.i
.PHONY : src/game/gameobject.cpp.i

src/game/gameobject.s: src/game/gameobject.cpp.s
.PHONY : src/game/gameobject.s

# target to generate assembly for a file
src/game/gameobject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/game/gameobject.cpp.s
.PHONY : src/game/gameobject.cpp.s

src/game/level.o: src/game/level.cpp.o
.PHONY : src/game/level.o

# target to build an object file
src/game/level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/game/level.cpp.o
.PHONY : src/game/level.cpp.o

src/game/level.i: src/game/level.cpp.i
.PHONY : src/game/level.i

# target to preprocess a source file
src/game/level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/game/level.cpp.i
.PHONY : src/game/level.cpp.i

src/game/level.s: src/game/level.cpp.s
.PHONY : src/game/level.s

# target to generate assembly for a file
src/game/level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/game/level.cpp.s
.PHONY : src/game/level.cpp.s

src/graphics/animation.o: src/graphics/animation.cpp.o
.PHONY : src/graphics/animation.o

# target to build an object file
src/graphics/animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/animation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/animation.cpp.o
.PHONY : src/graphics/animation.cpp.o

src/graphics/animation.i: src/graphics/animation.cpp.i
.PHONY : src/graphics/animation.i

# target to preprocess a source file
src/graphics/animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/animation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/animation.cpp.i
.PHONY : src/graphics/animation.cpp.i

src/graphics/animation.s: src/graphics/animation.cpp.s
.PHONY : src/graphics/animation.s

# target to generate assembly for a file
src/graphics/animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/animation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/animation.cpp.s
.PHONY : src/graphics/animation.cpp.s

src/graphics/layer.o: src/graphics/layer.cpp.o
.PHONY : src/graphics/layer.o

# target to build an object file
src/graphics/layer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/layer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/layer.cpp.o
.PHONY : src/graphics/layer.cpp.o

src/graphics/layer.i: src/graphics/layer.cpp.i
.PHONY : src/graphics/layer.i

# target to preprocess a source file
src/graphics/layer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/layer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/layer.cpp.i
.PHONY : src/graphics/layer.cpp.i

src/graphics/layer.s: src/graphics/layer.cpp.s
.PHONY : src/graphics/layer.s

# target to generate assembly for a file
src/graphics/layer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/layer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/layer.cpp.s
.PHONY : src/graphics/layer.cpp.s

src/graphics/sprite.o: src/graphics/sprite.cpp.o
.PHONY : src/graphics/sprite.o

# target to build an object file
src/graphics/sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/sprite.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/sprite.cpp.o
.PHONY : src/graphics/sprite.cpp.o

src/graphics/sprite.i: src/graphics/sprite.cpp.i
.PHONY : src/graphics/sprite.i

# target to preprocess a source file
src/graphics/sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/sprite.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/sprite.cpp.i
.PHONY : src/graphics/sprite.cpp.i

src/graphics/sprite.s: src/graphics/sprite.cpp.s
.PHONY : src/graphics/sprite.s

# target to generate assembly for a file
src/graphics/sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/sprite.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/sprite.cpp.s
.PHONY : src/graphics/sprite.cpp.s

src/graphics/tilelayer.o: src/graphics/tilelayer.cpp.o
.PHONY : src/graphics/tilelayer.o

# target to build an object file
src/graphics/tilelayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/tilelayer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/tilelayer.cpp.o
.PHONY : src/graphics/tilelayer.cpp.o

src/graphics/tilelayer.i: src/graphics/tilelayer.cpp.i
.PHONY : src/graphics/tilelayer.i

# target to preprocess a source file
src/graphics/tilelayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/tilelayer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/tilelayer.cpp.i
.PHONY : src/graphics/tilelayer.cpp.i

src/graphics/tilelayer.s: src/graphics/tilelayer.cpp.s
.PHONY : src/graphics/tilelayer.s

# target to generate assembly for a file
src/graphics/tilelayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/tilelayer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/tilelayer.cpp.s
.PHONY : src/graphics/tilelayer.cpp.s

src/graphics/tileset.o: src/graphics/tileset.cpp.o
.PHONY : src/graphics/tileset.o

# target to build an object file
src/graphics/tileset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/tileset.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/tileset.cpp.o
.PHONY : src/graphics/tileset.cpp.o

src/graphics/tileset.i: src/graphics/tileset.cpp.i
.PHONY : src/graphics/tileset.i

# target to preprocess a source file
src/graphics/tileset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/tileset.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/tileset.cpp.i
.PHONY : src/graphics/tileset.cpp.i

src/graphics/tileset.s: src/graphics/tileset.cpp.s
.PHONY : src/graphics/tileset.s

# target to generate assembly for a file
src/graphics/tileset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/tileset.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/tileset.cpp.s
.PHONY : src/graphics/tileset.cpp.s

src/graphics/tilesetpack.o: src/graphics/tilesetpack.cpp.o
.PHONY : src/graphics/tilesetpack.o

# target to build an object file
src/graphics/tilesetpack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/tilesetpack.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/tilesetpack.cpp.o
.PHONY : src/graphics/tilesetpack.cpp.o

src/graphics/tilesetpack.i: src/graphics/tilesetpack.cpp.i
.PHONY : src/graphics/tilesetpack.i

# target to preprocess a source file
src/graphics/tilesetpack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/tilesetpack.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/tilesetpack.cpp.i
.PHONY : src/graphics/tilesetpack.cpp.i

src/graphics/tilesetpack.s: src/graphics/tilesetpack.cpp.s
.PHONY : src/graphics/tilesetpack.s

# target to generate assembly for a file
src/graphics/tilesetpack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/graphics/tilesetpack.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/graphics/tilesetpack.cpp.s
.PHONY : src/graphics/tilesetpack.cpp.s

src/helper.o: src/helper.cpp.o
.PHONY : src/helper.o

# target to build an object file
src/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/helper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/helper.cpp.o
.PHONY : src/helper.cpp.o

src/helper.i: src/helper.cpp.i
.PHONY : src/helper.i

# target to preprocess a source file
src/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/helper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/helper.cpp.i
.PHONY : src/helper.cpp.i

src/helper.s: src/helper.cpp.s
.PHONY : src/helper.s

# target to generate assembly for a file
src/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/helper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/src/helper.cpp.s
.PHONY : src/helper.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal.dir/build.make CMakeFiles/brutal.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/graphic_test.o: test/graphic_test.cpp.o
.PHONY : test/graphic_test.o

# target to build an object file
test/graphic_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/test/graphic_test.cpp.o
.PHONY : test/graphic_test.cpp.o

test/graphic_test.i: test/graphic_test.cpp.i
.PHONY : test/graphic_test.i

# target to preprocess a source file
test/graphic_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/test/graphic_test.cpp.i
.PHONY : test/graphic_test.cpp.i

test/graphic_test.s: test/graphic_test.cpp.s
.PHONY : test/graphic_test.s

# target to generate assembly for a file
test/graphic_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/test/graphic_test.cpp.s
.PHONY : test/graphic_test.cpp.s

test/helper_test.o: test/helper_test.cpp.o
.PHONY : test/helper_test.o

# target to build an object file
test/helper_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/test/helper_test.cpp.o
.PHONY : test/helper_test.cpp.o

test/helper_test.i: test/helper_test.cpp.i
.PHONY : test/helper_test.i

# target to preprocess a source file
test/helper_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/test/helper_test.cpp.i
.PHONY : test/helper_test.cpp.i

test/helper_test.s: test/helper_test.cpp.s
.PHONY : test/helper_test.s

# target to generate assembly for a file
test/helper_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brutal_test.dir/build.make CMakeFiles/brutal_test.dir/test/helper_test.cpp.s
.PHONY : test/helper_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... brutal"
	@echo "... brutal_test"
	@echo "... src/game/gameobject.o"
	@echo "... src/game/gameobject.i"
	@echo "... src/game/gameobject.s"
	@echo "... src/game/level.o"
	@echo "... src/game/level.i"
	@echo "... src/game/level.s"
	@echo "... src/graphics/animation.o"
	@echo "... src/graphics/animation.i"
	@echo "... src/graphics/animation.s"
	@echo "... src/graphics/layer.o"
	@echo "... src/graphics/layer.i"
	@echo "... src/graphics/layer.s"
	@echo "... src/graphics/sprite.o"
	@echo "... src/graphics/sprite.i"
	@echo "... src/graphics/sprite.s"
	@echo "... src/graphics/tilelayer.o"
	@echo "... src/graphics/tilelayer.i"
	@echo "... src/graphics/tilelayer.s"
	@echo "... src/graphics/tileset.o"
	@echo "... src/graphics/tileset.i"
	@echo "... src/graphics/tileset.s"
	@echo "... src/graphics/tilesetpack.o"
	@echo "... src/graphics/tilesetpack.i"
	@echo "... src/graphics/tilesetpack.s"
	@echo "... src/helper.o"
	@echo "... src/helper.i"
	@echo "... src/helper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/graphic_test.o"
	@echo "... test/graphic_test.i"
	@echo "... test/graphic_test.s"
	@echo "... test/helper_test.o"
	@echo "... test/helper_test.i"
	@echo "... test/helper_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

